# Generated by Django 4.1 on 2023-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('num_rooms', models.PositiveIntegerField()),
                ('num_guests', models.PositiveIntegerField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('today_date', models.DateField()),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
