# Generated by Django 4.1 on 2023-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_invoice_num_guests_remove_invoice_num_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='package_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
