# Generated by Django 4.1 on 2023-04-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0023_alter_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
