# Generated by Django 4.1 on 2023-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0025_alter_team_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='todo',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
