# Generated by Django 4.1 on 2023-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0026_team_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='todo',
            field=models.CharField(default='text box', max_length=500),
        ),
    ]
