# Generated by Django 4.1 on 2023-04-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0027_alter_team_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='todo',
            field=models.CharField(max_length=500),
        ),
    ]
