# Generated by Django 4.1 on 2023-05-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0028_alter_team_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=1000000, null=True),
        ),
    ]
