# Generated by Django 4.1 on 2023-05-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0029_alter_team_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='advanced',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=1000000, null=True),
        ),
    ]
