# Generated by Django 4.1 on 2023-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0030_team_advanced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='package',
            field=models.CharField(choices=[('Bubble Maker', 'Bubble Maker '), ('Seal Team', 'Seal Team'), ('Open Water Diver', 'Open Water Diver'), ('Adventure Diver', 'Adventure Diver'), ('Advanced Open Water Diver', 'Advanced Open Water Diver'), ('EFR Primary & Secondary Care', 'EFR Primary & Secondary Care'), ('Rescue Diver', 'Rescue Diver'), ('Divemaster', 'Divemaster'), ('Deep Diver', 'Deep Diver'), ('Digital Underwater Photography', 'Digital Underwater Photography'), ('Enriched Air Diver', 'Enriched Air Diver'), ('Night Diver', 'Night Diver'), ('Adaptive Support Diver', 'Adaptive Support Diver'), ('Adaptive Techniques', 'Adaptive Techniques'), ('DSMB Diver', 'DSMB Diver'), ('Emergency Oxygen Provider', 'Emergency Oxygen Provider'), ('Underwater Navigator', 'Underwater Navigator'), ('Wreck Diver', 'Wreck Diver'), ('Peak Performance Buoyancy', 'Peak Performance Buoyancy'), ('Fun Dive Package', 'Fun Dive Package'), ('Fun Dive + Course Package', 'Fun Dive + Course Package'), ('Open Water Dive Course Package', 'Open Water Dive Course Package'), ('Advanced Open Water Diver Course Package', 'Advanced Open Water Diver Course Package'), ('Open & Advanced Open Water Diver Course', 'Open & Advanced Open Water Diver Course'), ('Open Water To Divemaster', 'Open Water To Divemaster'), ('Explore Lakshadweep', 'Explore Lakshadweep')], max_length=240),
        ),
    ]
