# Generated by Django 4.1 on 2023-06-18 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0031_alter_team_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hotelname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
