# Generated by Django 4.1 on 2023-06-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0033_hotelmanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='hotelname',
        ),
    ]
