# Generated by Django 4.1 on 2023-06-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0034_remove_team_hotelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicantform.hotelmanage'),
        ),
    ]
