# Generated by Django 4.1 on 2023-06-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantform', '0035_alter_team_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicantform.hotelmanage'),
        ),
    ]
